### ISSUE TITLE
Error on deleting a service with File inputs

### ISSUE THREAD

**Issue by vincent-lefort** [lirmm/waves-core#1]
It's impossible to delete a service with a "File input". It raise this error :
Cannot query "Data type (ListParam)": Must be "FileInput" instance.

There is a workaround: go on submissions methods, delete all "File inputs" one by one, then go back to services page to delete the service.

All error report**
ValueError at /admin/wcore/service/
Cannot query "Data type (ListParam)": Must be "FileInput" instance.
Request Method: 	POST
Request URL: 	http://127.0.0.1:8000/admin/wcore/service/
Django Version: 	1.11.14
Exception Type: 	ValueError
Exception Value:
Cannot query "Data type (ListParam)": Must be "FileInput" instance.
Exception Location: 	/home/milanesi/.venvs/wavescoreenv/local/lib/python2.7/site-packages/django/db/models/sql/query.py in check_query_object_type, line 1054
Python Executable: 	/home/milanesi/.venvs/wavescoreenv/bin/python
Python Version: 	2.7.12
Python Path:
['/home/milanesi/Documents/WAVES/Formations/TP_WAVES/waves',
'/home/milanesi/.venvs/wavescoreenv/lib/python2.7',
'/home/milanesi/.venvs/wavescoreenv/lib/python2.7/plat-x86_64-linux-gnu',
'/home/milanesi/.venvs/wavescoreenv/lib/python2.7/lib-tk',
'/home/milanesi/.venvs/wavescoreenv/lib/python2.7/lib-old',
'/home/milanesi/.venvs/wavescoreenv/lib/python2.7/lib-dynload',
'/usr/lib/python2.7',
'/usr/lib/python2.7/plat-x86_64-linux-gnu',
'/usr/lib/python2.7/lib-tk',
'/home/milanesi/.venvs/wavescoreenv/local/lib/python2.7/site-packages',
'/home/milanesi/.venvs/wavescoreenv/lib/python2.7/site-packages']

**Comment by marcoooo** [comment]
Sorry I could not reproduce. Can you be more specific ? (sent email with screenshots)

Though I found another issue while searching for this one. The delete button was active but with no effect. 
https://github.com/lirmm/waves-core/pull/9

**Comment by vincent-lefort** [comment]
From WAVES back-office: 'Home' click 'Services'.
Select a service with the check-box then select 'Delete selected services' in the 'Action' dropdown list and click the 'Go' button. This raises the error.
![waves_issue1](https://user-images.githubusercontent.com/20642657/49499485-75b9c500-f86e-11e8-8758-2749ee55effc.png)
