### ISSUE TITLE
Decimal step settings are ignored in Inputs 

### ISSUE THREAD

**Issue by bockp** [lirmm/waves-core#14]
When configuring a Decimal Input for a service, one can set the minimum and maximum, as well as the steps used by said service.

The step setting is supposed to affect what the Browsers up and down buttons increment/decrement the value in the field by:

![screenshot from 2019-01-11 10-50-30](https://user-images.githubusercontent.com/10536344/51026432-cb307280-158e-11e9-82a5-61cb2ad7ac15.png)

As it is, no matter the value placed in the Step field in the Input configuration screen:

![image](https://user-images.githubusercontent.com/10536344/51026659-4f82f580-158f-11e9-947b-ab3fef1a978e.png)

On the user's side (as well as in the Preview when logged in as Admin), the Incrementation step will always be 1.

# Steps to Reproduce:

1. Create service (using LocalShellAdaptor)
2. Edit the Default submission method
3. Add a Decimal Input, and configure it's step to be any value other than 1
4. Use Preview button and the Stepper buttons to try and increment/decrement the value.

-------------
Tested on both Firefox and Chrome, so not a Browser-specific issue.

Not a high priority bug, I know, but still needs to be documented somewhere.
Once I've finished adding bugs and observations in the Issues, If I have the time I'll take a stab at fixing it on our local install and adding the fix to a Fork, then doing a Pull Request mentioning the issues, but I don't know where the different parts to fix are located, so might not be too optimal.

Have a good day, and thanks for the awesome job on Waves !

Peter.

**Comment by marcoooo** [comment]
Thanks Peter for any help you could provide ! I am not actually working on WAVES full time. But would be happy to help if you need more info to debug.

**Comment by bockp** [comment]
As far as I can see in the Inspector there are no errors

here's what the HTML looks like when the service is configured to a step of 0.01 for the pval input:

<input type="number" name="pval" value="0.05" step="any" required="" min="0.000" max="1.000" title="P value threshold For the Wilcoxon test." class="numberinput form-control" id="id_pval">

So it looks like it ignores the step setting and just puts "any" instead (which defaults to 1).

**Comment by marcoooo** [comment]
Fixed in 1.6.6
