### ISSUE TITLE
Delete buttons redirects to wrong links

### ISSUE THREAD

**Issue by bockp** [lirmm/waves-core#15]
The delete buttons on Service, Job, Infrastructure and Api Auths configuration pages are broken.

Here's an example showing the Delete button on a Service, and the link it redirects to:

![screenshot from 2019-01-11 14-38-40](https://user-images.githubusercontent.com/10536344/51036920-e612df00-15ae-11e9-9166-76ebedcb3efd.png)

Here are the links I get from the different instances of this bug, and the links I expected to get (Which, I've tested, exist and are functional, just not accessible using the Buttons)
(CAPS indicate variable elements of the links)

|                               Actual                              	|                              Expected                             	|
|:-----------------------------------------------------------------:	|:-----------------------------------------------------------------:	|
|           http://SITE/admin/wcore/service/ID/change/          	|           http://SITE/admin/wcore/service/ID/delete/          	|
|             http://SITE/admin/wcore/job/ID/change/            	|             http://SITE/admin/wcore/job/ID/delete/            	|
|           http://SITE/admin/wcore/runner/ID/change/           	|           http://SITE/admin/wcore/runner/ID/delete/           	|
| http://SITE/admin/authentication/wavesapiuser/API_KEY/change/ 	| http://SITE/admin/authentication/wavesapiuser/API_KEY/delete/ 	|

**Comment by marcoooo** [comment]
Thanks.
