### ISSUE TITLE
File Input samples are visible even when File Input is hidden

### ISSUE THREAD

**Issue by bockp** [lirmm/waves-core#16]
When I configure a File Input as being dependent on a certain list value, and that list value is not selected, any Sample files related to that File Input still appears in the window.

![image](https://user-images.githubusercontent.com/10536344/51039841-6f79df80-15b6-11e9-99f8-4d1375ab3fe4.png)

![image](https://user-images.githubusercontent.com/10536344/51039878-84567300-15b6-11e9-849d-b0833b49d05d.png)

# Steps to Reproduce:

1. Create a service
2. Create a Submission Method
3. Create a List input with values on|1 and off|0
4. Create a File Input _without_ the copy-paste enabled 
5. Set the File input to have a sample file
6. Set the File input so that Sample dependency is linked to the List Input, with value "1"

If Copy-paste _is_ enabled in the file input, it works as expected : 

![image](https://user-images.githubusercontent.com/10536344/51039939-a05a1480-15b6-11e9-9b42-03266febb195.png)
![image](https://user-images.githubusercontent.com/10536344/51039995-b23bb780-15b6-11e9-9691-8f661410f7ea.png)

**Comment by marcoooo** [comment]
Next version was supposed to come with a proper Javascript library managing properly display / hide functionalities. Unfortunately, I didn't find time lately to work on it. Hope will find soon.

**Comment by marcoooo** [comment]
I think this has been fixed with release 1.6.5.
